class Solution {
    public int numSubarrayProductLessThanK(int[] nums, int k) {
        int c = 0;
        int p = 1;
        int si = 0;
        int ei = 0;
        while(ei < nums.length){
            p *= nums[ei];
            //shrink window - 
            while(p >= k && si<=ei){
                p /= nums[si];
                si++;
            }
            // number of subarrays generated by inclusion of a single element is not 1 it's (e--si+1);
            c += (ei-si +1);
            ei++;

        }
        return c;
    }
}